/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.mapstruct.lombok;

import org.junit.jupiter.api.Test;

import gradle.mapstruct.lombok.domain.Target;
import gradle.mapstruct.lombok.dto.Source;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
    	Source src = new Source();
    	src.setNumber(10);
    	
		Target target = Library.INSTANCE.map(src);
		
		assertEquals(target.getNumber(), "10");
    }
}
