/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.mapstruct.lombok;

import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

import gradle.mapstruct.lombok.domain.Target;
import gradle.mapstruct.lombok.dto.Source;

@Mapper
public interface Library {
	Library INSTANCE = Mappers.getMapper(Library.class);
	
	Target map(Source src);
}
